"""correct table name

Revision ID: c325aeb09efe
Revises: 0f95400106ce
Create Date: 2025-09-27 19:47:35.291199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c325aeb09efe'
down_revision: Union[str, Sequence[str], None] = '0f95400106ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('model_year', sa.Integer(), nullable=False))
    op.drop_column('cars', 'mode_year')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('mode_year', sa.INTEGER(), nullable=False))
    op.drop_column('cars', 'model_year')
    # ### end Alembic commands ###
